<?php
$table_columns = array(
    "id" => array("char", ""),
    "mobile" => array("varchar", ""),
    "username" => array("varchar", ""),
    "password" => array("char", ""),
    "name" => array("varchar", ""),
    "alias" => array("varchar", ""),
    "hader_img" => array("varchar", ""),
    "department" => array("text", ""),
    "role_id" => array("char", "0"),
    "sort" => array("int", 0),
    "position" => array("varchar", ""),
    "gender" => array("tinyint", 1),
    "email" => array("varchar", ""),
    "biz_mail" => array("varchar", ""),
    "telephone" => array("varchar", ""),
    "is_leader_in_dept" => array("text", ""),
    "direct_leader" => array("varchar", ""),
    "external_position" => array("varchar", ""),
    "address" => array("varchar", ""),
    "main_department" => array("char", ""),
    "apptoken" => array("varchar", ""),
    "is_del" => array("tinyint", 0)
);