CREATE TABLE `javatodo_coupon` (
  `id` char(25) NOT NULL DEFAULT '',
  `name` varchar(255) NOT NULL DEFAULT '' ,
  `is_common_use` tinyint(4) NOT NULL DEFAULT '0' ,
  `store_id` char(25) NOT NULL DEFAULT '' ,
  `store_group_id` char(25) NOT NULL DEFAULT '' ,
  `type` tinyint(4) NOT NULL DEFAULT '1' ,
  `order_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `total` int(11) NOT NULL DEFAULT '10' ,
  `limit_num` int(11) NOT NULL ,
  `way` tinyint(4) NOT NULL DEFAULT '1' ,
  `reduce_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `discount` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `full_reduce_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `rebate_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `rebate_integral` int(11) NOT NULL DEFAULT '0' ,
  `rebate_type` tinyint(4) NOT NULL DEFAULT '1' ,
  `is_receive_link` tinyint(4) NOT NULL DEFAULT '0' ,
  `add_to_coupon_center` tinyint(4) NOT NULL DEFAULT '0' ,
  `send_start_time` bigint(20) NOT NULL DEFAULT '0' ,
  `send_end_time` bigint(20) NOT NULL DEFAULT '0' ,
  `spend_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `spend_integral` int(11) NOT NULL DEFAULT '0' ,
  `is_limit_member_level` tinyint(4) NOT NULL DEFAULT '0' ,
  `member_level_ids` varchar(255) NOT NULL ,
  `use_start_time` bigint(20) NOT NULL DEFAULT '0' ,
  `use_end_time` bigint(20) NOT NULL DEFAULT '0' ,
  `add_time` bigint(20) NOT NULL DEFAULT '0' ,
  `available_modules` varchar(1000) NOT NULL DEFAULT '' ,
  `is_open` tinyint(4) NOT NULL DEFAULT '1' ,
  `is_del` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4