CREATE TABLE `javatodo_malltodo_merchant` (
  `id` char(25) NOT NULL DEFAULT '',
  `agent_id` char(25) NOT NULL,
  `malltodo_account` varchar(32) NOT NULL DEFAULT '' ,
  `merchant_name` varchar(99) NOT NULL DEFAULT '',
  `xinyongdaima` varchar(25) NOT NULL DEFAULT '' ,
  `yingyezhizhao` varchar(255) NOT NULL DEFAULT '' ,
  `zhizhao_endtime` bigint(20) NOT NULL DEFAULT '0' ,
  `web_name` varchar(25) NOT NULL ,
  `root_domain` varchar(25) NOT NULL DEFAULT '' ,
  `database_user` char(16) NOT NULL DEFAULT '',
  `database_password` char(16) NOT NULL DEFAULT '',
  `mobile` varchar(25) NOT NULL DEFAULT '',
  `password` char(32) NOT NULL DEFAULT '',
  `logo` varchar(255) NOT NULL DEFAULT '' ,
  `address` varchar(255) NOT NULL DEFAULT '',
  `lng` double NOT NULL DEFAULT '0',
  `lat` double NOT NULL DEFAULT '0',
  `pid` char(25) NOT NULL DEFAULT '',
  `ppid` char(25) NOT NULL DEFAULT '',
  `pppid` char(25) NOT NULL DEFAULT '',
  `recommend_code` varchar(25) NOT NULL DEFAULT '' ,
  `web_poster` varchar(255) NOT NULL DEFAULT '' ,
  `createtime` bigint(20) NOT NULL DEFAULT '0',
  `money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `money_0` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `money_1` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `integral` int(11) NOT NULL DEFAULT '0',
  `readme_time` bigint(20) NOT NULL DEFAULT '0',
  `is_need_create_website` tinyint(4) NOT NULL DEFAULT '0' ,
  `is_create_website` tinyint(4) NOT NULL DEFAULT '0' ,
  `is_del` tinyint(3) unsigned NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `malltodo_account` (`malltodo_account`),
  UNIQUE KEY `web_name` (`web_name`),
  UNIQUE KEY `mobile` (`mobile`),
  KEY `idx_shareid` (`pid`) USING BTREE,
  KEY `agent_id` (`agent_id`),
  KEY `is_need_create_website` (`is_need_create_website`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4