CREATE TABLE `javatodo_malltodo_service_order` (
  `id` char(25) NOT NULL DEFAULT '',
  `merchant_id` char(25) NOT NULL DEFAULT '',
  `service_name` varchar(25) NOT NULL DEFAULT '',
  `service` varchar(99) NOT NULL,
  `is_experience` tinyint(4) NOT NULL DEFAULT '0',
  `num` int(11) NOT NULL ,
  `unit` varchar(5) NOT NULL ,
  `addtime` bigint(20) NOT NULL DEFAULT '0',
  `order_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `discount` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `all_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `pay_type` tinyint(4) NOT NULL DEFAULT '0' ,
  `pay_channel` varchar(25) NOT NULL DEFAULT '' ,
  `paytime` bigint(20) NOT NULL DEFAULT '0',
  `paydate` date NOT NULL DEFAULT '0000-00-00',
  `transaction_id` varchar(32) NOT NULL DEFAULT '',
  `status` tinyint(4) NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4