CREATE TABLE `javatodo_order_dish_cart` (
  `id` char(25) NOT NULL DEFAULT '',
  `uid` char(25) NOT NULL DEFAULT '',
  `username` varchar(32) NOT NULL ,
  `headimg` varchar(255) NOT NULL ,
  `restaurant_id` char(25) NOT NULL ,
  `category_id` char(25) NOT NULL DEFAULT '',
  `food_id` char(25) NOT NULL DEFAULT '',
  `sku_food_id` char(25) NOT NULL DEFAULT '',
  `food_name` varchar(120) NOT NULL DEFAULT '',
  `pic` varchar(255) NOT NULL DEFAULT '' ,
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `num` int(11) NOT NULL DEFAULT '0' ,
  `food_all_money` decimal(10,2) NOT NULL,
  `sku` text NOT NULL,
  `seat_id` char(25) NOT NULL DEFAULT '' ,
  `seat_name` varchar(25) NOT NULL DEFAULT '' ,
  `seat_area_type` tinyint(4) NOT NULL DEFAULT '0',
  `restaurant_uid` char(25) NOT NULL DEFAULT '' ,
  `remark` varchar(255) NOT NULL ,
  `feie_user` varchar(32) NOT NULL ,
  `feie_ukey` varchar(32) NOT NULL ,
  `feie_sn` varchar(32) NOT NULL ,
  `feie_sim` varchar(25) NOT NULL ,
  `is_print` tinyint(4) NOT NULL DEFAULT '0' ,
  `status` tinyint(4) NOT NULL DEFAULT '0' ,
  `is_del` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4