CREATE TABLE `javatodo_order_dish_order` (
  `id` char(25) NOT NULL DEFAULT '',
  `order_sn` varchar(32) DEFAULT NULL ,
  `uid` char(25) NOT NULL DEFAULT '',
  `restaurant_id` char(25) NOT NULL DEFAULT '' ,
  `restaurant_uid` char(25) NOT NULL DEFAULT '',
  `addtime` bigint(20) NOT NULL DEFAULT '0',
  `pay_type` tinyint(4) NOT NULL DEFAULT '0' ,
  `pay_channel` varchar(25) NOT NULL ,
  `paytime` bigint(20) NOT NULL DEFAULT '0' ,
  `paydate` date NOT NULL DEFAULT '0000-00-00',
  `transaction_id` varchar(32) NOT NULL DEFAULT '',
  `all_food_money` decimal(10,2) DEFAULT '0.00' ,
  `discount` decimal(10,2) DEFAULT '0.00' ,
  `coupon_way` tinyint(4) NOT NULL DEFAULT '0' ,
  `coupon_user_id` char(25) NOT NULL DEFAULT '',
  `coupon_name` varchar(255) NOT NULL DEFAULT '' ,
  `coupon_reduce_money` decimal(10,2) NOT NULL ,
  `coupon_rebate_money` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `coupon_rebate_integral` int(11) NOT NULL DEFAULT '0' ,
  `coupon_rebate_status` tinyint(4) NOT NULL DEFAULT '0' ,
  `coupon_store_id` char(25) NOT NULL DEFAULT '' ,
  `all_money` decimal(10,2) DEFAULT '0.00' ,
  `income` decimal(10,2) NOT NULL DEFAULT '0.00' ,
  `seat_name` varchar(25) NOT NULL DEFAULT '' ,
  `seat_id` char(25) NOT NULL DEFAULT '',
  `seat_area_type` tinyint(4) NOT NULL DEFAULT '0',
  `status` tinyint(3) DEFAULT '0' ,
  `is_del` tinyint(3) DEFAULT '0' ,
  PRIMARY KEY (`id`),
  KEY `addtime` (`addtime`),
  KEY `paytime` (`paytime`),
  KEY `paydate` (`paydate`),
  KEY `status` (`status`),
  KEY `is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4